JWT gem
Charchit507/jaipur-sweets pull request #1
Opened 2022-09-14 12:47 UTC by Charchit507

2022-09-15 10:16 UTC, neeteshgupta95 requested changes

2022-09-15 10:16 UTC, neeteshgupta95 commented on app/controllers/concerns/json_web_token.rb
> +  SECRET_KEY = Rails.application.secret_key_base
move this to `credentials.yml.enc` file and use as a variable

2022-09-15 10:16 UTC, neeteshgupta95 commented on app/controllers/users_controller.rb
> +  # end
why commented code?

2022-09-15 10:16 UTC, neeteshgupta95 commented on app/controllers/users_controller.rb
> +  end
are we listing users?

2022-09-15 10:16 UTC, neeteshgupta95 commented on config/routes.rb
> +  resource :users
why `resource`

2022-09-15 10:16 UTC, neeteshgupta95 commented on db/migrate/20220915091245_create_users.rb
> +      t.string :email
add uniqueness at the database level

2022-09-15 10:16 UTC, neeteshgupta95 commented on app/models/user.rb
> +  validates :email, presence: true
add uniqueness and email regex as well

2022-09-15 10:16 UTC, neeteshgupta95 commented on app/controllers/users_controller.rb
> +    @user = User.new(user_params)
remove that instance variable, use local variable instead

2022-09-15 10:16 UTC, neeteshgupta95 commented on app/controllers/application_controller.rb
> +before_action :authenticate_request
include that at the top of the file

2022-09-15 11:24 UTC, Charchit507 commented on config/routes.rb
> +  resource :users
sir only show, create, update and delete ke routes show krwane hai na

2022-09-15 14:48 UTC, neeteshgupta95 commented on config/routes.rb
> +  resource :users
ok

2022-09-15 17:43 UTC, neeteshgupta95 requested changes

2022-09-15 17:43 UTC, neeteshgupta95 commented on app/controllers/users_controller.rb
> +    render json: user, status: :ok
are you able to get the value of `user` here?

2022-09-15 17:43 UTC, neeteshgupta95 commented on app/controllers/users_controller.rb
> +    user.destroy
are you able to get the value of user here?

2022-09-15 17:43 UTC, neeteshgupta95 commented on config/routes.rb
> +  resources :users
use only to those actions, which we are using

2022-09-15 17:43 UTC, neeteshgupta95 commented on app/controllers/application_controller.rb
> +      @current_user = User.find(decoded[:user_id])
do indentation

2022-09-16 08:41 UTC, neeteshgupta95 approved these changes

2022-09-16 08:41 UTC, merged